name: ci

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
    paths-ignore:
      - "README.md"

jobs:
  check:
    name: nix flake check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: cachix/install-nix-action@v31
      - run: nix flake check path:.

  build:
    name: build x86 systems
    runs-on: ubuntu-latest
    strategy:
      matrix:
        configuration: [
            # "home-goe",
            "home-ber",
          ]
    steps:
      # - uses: jlumbroso/free-disk-space@main
      - uses: actions/checkout@v7
      - uses: cachix/install-nix-action@v31
      - run: nix build .#nixosConfigurations.${{ matrix.configuration }}.config.system.build.toplevel
